import type { Metadata } from "next";

import { ThemeProvider } from "@/components/theme-provider";
import { NeueHaas } from "@/lib/fonts";

import "./globals.css";
import { GsapAnimator } from "@/components/motion/gsap-animator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${NeueHaas.variable} antialiased`}>
          <GsapAnimator/>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
